### ISSUE TITLE
Does the tree tool search shortest proofs?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [wo/tpg#11]
What is the search strategy for proofs? Some iterative
deepening. Here is a funny example, where I find a 
shorter regular proof for FOL with equality, its a validation 

proof, not a refutation falsification, so opposite formula signs:

![Unbenannt2](https://user-images.githubusercontent.com/95891213/149742632-0ffab477-086c-4e93-a0aa-fa395ee2cb16.PNG)

On the other hand the tree tools does one more LL:

https://www.umsu.de/trees/#~6x~6y~6z~6tp%28x,y,z,t%29=p%28y,z,t,x%29~5p%28a,b,c,d%29=p%28c,d,a,b%29
![Unbenannt](https://user-images.githubusercontent.com/95891213/149742667-5c9979ee-02f1-44a7-968c-6b2c845bc676.PNG)

**Comment by wo** [comment]
Yes, the internal proof search uses iterative deepening, but it doesn't try out all possible proofs of a given size, as that would take prohibitively long. When a proof is found, I try to strip any redundant elements, but the result isn't always the simplest possible proof. The equality reasoner seems to have a preference for closing trees with formulas of the type ~(t=t). I might look into whether this can be changed, but it's not a priority.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, I see, it closes with (refl) and not with (ax). In my prover I
have ✓, but recently I also wrote whether its (ax) or (refl).
Interesting, the different outcome. I am searching first for (ax),

and the for (refl), but neither go into the budget of iterative
depening. But (subst) does so, although I have only one counter,
and not multiple counters or some such refinement.
