### ISSUE TITLE
Parsing problems equality and numbers

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [wo/tpg#12]
I can do:

a=b → f(a)=f(b) is valid.
https://www.umsu.de/trees/#a=b~5f%28a%29=f%28b%29

But I cannot do:

Input 0=1 → f(0)=f(1), I then get:
=01 → f(0)=f(1) is invalid.
https://www.umsu.de/trees/#0=1~5f%280%29=f%281%29

But I guess its a parsing problem, because this works:

Input instead =(0,1) → f(0)=f(1), I then get
0=1 → f(0)=f(1) is valid.
https://www.umsu.de/trees/#=%280,1%29~5f%280%29=f%281%29

**Comment by wo** [comment]
Officially, you're not supposed to use numerals as individual constants, because I want to allow for numerals as predicate "subscripts": P1a, P2a etc. If numerals can be constants as well as predicate subscripts, these are ambiguous. But I wonder if anyone wants to use the numerical subscripts.

**Comment by Jean-Luc-Picard-2021** [comment]
It was handy for Peano, and proving commutativity.
Now I wish for infix + operator, would make this more readable:

> 1) First prove by induction that ∀x(0 + x = x).
> Base Case: 0 + 0 = 0
> ∀xa(x,0)=x → a(0,0)=0 is valid.
> Induction Step: 0 + x = x => 0 + s(x) = s(x)
> ∀x∀ya(x,s(y))=s(a(x,y)) → ∀x(a(0,x)=x → a(0,s(x))=s(x)) is valid.
>
> 2) Now prove by induction that ∀x∀y(s(y) + x = s(y + x))
> Base Case: ∀y(s(y) + 0 = s(y + 0))
> ∀xa(x,0)=x → ∀ya(s(y),0)=s(a(y,0)) is valid.
> Induction Step: ∀y(s(y) + x = s(y + x)) => ∀y(s(y) + s(x) = s(y + s(x)))
> ∀x∀ya(x,s(y))=s(a(x,y)) → ∀x(∀ya(s(y),x)=s(a(y,x)) → ∀ya(s(y),s(x))=s(a(y,s(x)))) is valid.
>
> 3) Finally prove by induction that ∀x∀y(x + y = y + x)
> Base Case: 0 + y = y + 0, using 1)
> (∀xa(x,0)=x ∧ ∀xa(0,x)=x) → ∀ya(0,y)=a(y,0) is valid.
> Induction Step: x + y = y + x => s(x) + y = y + s(x), using 2)
> (∀x∀ya(x,s(y))=s(a(x,y)) ∧ ∀x∀ya(s(y),x)=s(a(x,y))) → ∀x(∀ya(x,y)=a(y,x) → ∀ya(s(x),y)=a(y,s(x))) is valid.

**Comment by medovina** [comment]
I agree that having numerals as constants would be convenient.  Given the choice, I'd probably take these over predicate subscripts.

**Comment by medovina** [comment]
Thanks for the fix!  In my opinion this is a nice change.

**Comment by medovina** [comment]
Of course, it is now slightly confusing that in a countermodel the integers in the domain might not match the names of constants.  For example, if I type

```
x = 0
```

then I see

```
x=0 is invalid.

Countermodel:
Domain:	{ 0, 1 }
x: 0
0: 1
```

It would be nicer if the system found a countermodel in which integer constants had their actual values, e.g.

```
x=0 is invalid.

Countermodel:
Domain:	{ 0, 1 }
x: 1
```

However, I recognize that that might be a non-trivial change.

**Comment by medovina** [comment]
Hm - yes, that's a tricky example.

As one possible workaround, the domain in a countermodel could contain distinct values d<sub>0</sub>, d<sub>1</sub> and so on, rather than integers.  Then in response to

x = 0

the user might see this:

x=0 is invalid.

Countermodel:
Domain:	{ d<sub>0</sub>, d<sub>1</sub> }
x: d<sub>0</sub>
0: d<sub>1</sub>

You could display the countermodel elements in this way if the query includes any integer constants.  Otherwise, you could just use integers as you do today.

Perhaps that would be slightly clearer than the current behavior.

**Comment by wo** [comment]
That looks like a good idea, thanks.
