### ISSUE TITLE
Example that sends tree tool into nirwana

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [wo/tpg#13]
I tried this here:

> ∀x(m(e,x)=x)∧∀x(m(i(x),x)=e)∧∀x∀y∀z(m(m(x,y),z)=m(x,m(y,z)))→∀x(m(x,e)=x)
https://www.umsu.de/trees/#~6x(m(e,x)=x)~1~6x(m(i(x),x)=e)~1~6x~6y~6z(m(m(x,y),z)=m(x,m(y,z)))~5~6x(m(x,e)=x)

But it gets very quickly into a state where stop buttion doesn't work anymore.

Bug or feature?

**Comment by wo** [comment]
Can confirm. The equality reasoner appears to get stuck in step 4350.

**Comment by Jean-Luc-Picard-2021** [comment]
Howdy? Ever managed to prove this (Pelletier 53):

(∃X∃Y(¬ (X = Y) ∧ ∀Z(Z = X ∨ Z = Y)) → 
(∃T∀U(∃V∀W(f(U, W) ↔ W = V) ↔ U = T) ↔ 
∃V∀W(∃T∀U(f(U, W) ↔ U = T) ↔ W = V)))

Its not sending the prover to nirvana, but somehow
I have the feeling its more busy with counter model
finding than proving.

**Comment by wo** [comment]
Right. If I turn off the model search, it still runs up to step 335,000 at which point my computer runs out of memory.

**Comment by Jean-Luc-Picard-2021** [comment]
SPASS can find a proof, but it is a resolution proof:

[https://webspass.spass-prover.org/cgi-bin/webspass](https://webspass.spass-prover.org/cgi-bin/webspass)
