### ISSUE TITLE
Feature request: persistency aka monotonic accessibility checkbox

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [wo/tpg#19]
I wanted to experiment with a certain Kripke semantics
for intuitionistic logic. But I am missing a check box to
choose a persistency condtion for the accessibility relation. 

This would be a property that can be expressed by this
axiom schema, but you can also express it directly with the
accessibility relation, see [here](https://en.wikipedia.org/wiki/Kripke_semantics#Semantics_of_intuitionistic_logic):
```
P => []P
```
The workaround is currently to do for example this, i.e.
manually instantiate and box prefix the axiom schema for each
propositional variable and use the standard translation `S(_)`:

> (□(p→□p) ∧ □(q→□q)) → (□(□(p→q) → p) → p) is invalid.
> https://www.umsu.de/trees/#~8(p~5~8p)~1~8(q~5~8q)~5(~8(~8(p~5q)~5p)~5p)||reflexivity|transitivity

Or alternatively use the Gödel translation `T(_)`:

> □(□(□p → □q) → □p) → □p is invalid.
> https://www.umsu.de/trees/#~8%28~8%28~8p~5~8q%29~5~8p%29~5~8p||reflexivity|transitivity

The models under the Gödel translation `T(_)` do not directly
correspond to models from the Kripke semantics
for intuitionistic logic with the persistency condtion.

So the advantage of the `S(_)` translation plus persistency
condition is focus on different counter models.

**Comment by Jean-Luc-Picard-2021** [comment]
P.S.: There is a kind of Galois Connection between the 
standard translation S(_) and the Gödel translation T(_).

See also:

> **Modal Logic - Logic Guides 35**
> Lemma 3.81 (Skeleton)
> Chagrov & Zakharyaschev - 1997
> https://www.amazon.de/dp/0198537794

**Comment by Jean-Luc-Picard-2021** [comment]
There is an additional benefit, the search is much faster. Here
is an example. 

Screenshot 1: Counter Model via S(_) Translation

**Comment by wo** [comment]
Thanks for the suggestion. It's not trivial to implement. At the moment, my countermodel finder uses the standard translation to turn modal sentences into first-order sentences; accessibility conditions are translated into further premises. I don't think the persistency condition is first-order definable, so I couldn't handle it in this way. (I'd also need a new tree rule.)

**Comment by Jean-Luc-Picard-2021** [comment]
It depends how you translate. If you translate a propositional variable p
into p(w) its a little bit more effort. If you translate a propositional variable
p into D(p,w) then its a little bit less effort:
```
ALL(p):ALL(w):ALL(v):[D(w,p) & R(w,v) => D(v,p)]
```
For p(w) you can collect all propositional variables from the given
input A, lets say they are p1,..,pn. And then generate:
```
ALL(w):ALL(v):[p1(w) & R(w,v) => p1(v)]
[...]
ALL(w):ALL(v):[pn(w) & R(w,v) => pn(v)]
```
My claims are based on this short wiki definition:

**Semantics of intuitionistic logic**
https://en.wikipedia.org/wiki/Kripke_semantics#Semantics_of_intuitionistic_logic

In the above D(p,w) is written as w ⊩ p .

**Comment by wo** [comment]
The problem is that propositional quantification is second-order quantification.

**Comment by Jean-Luc-Picard-2021** [comment]
Well you reify the prositional variables. So the propositional variables
p1,..,pn land in some domain P, the forcing conditions, and for
every propositional variable pj there is a forcing condition Pj e P.

So basically this here, would be rather a multisorted
thing, were W is the sort of the possible worlds, and P
are the forcing conditions. So turn this:
```
ALL(p):ALL(w):ALL(v):[D(w,p) & R(w,v) => D(v,p)]
```
Into this:
```
ALL(p):[P(p) => ALL(w):[W(w) => ALL(v):[W(v) => [D(w,p) & R(w,v) => D(v,p)]]]
```

**Comment by Jean-Luc-Picard-2021** [comment]
> ```
> ALL(w):ALL(v):[p1(w) & R(w,v) => p1(v)]
> [...]
> ALL(w):ALL(v):[pn(w) & R(w,v) => pn(v)]
> ```
