### ISSUE TITLE
The converse Buridan formula is shown to be invalid

### ISSUE THREAD

**Issue by MichaelRushton** [wo/tpg#22]
https://en.wikipedia.org/wiki/Buridan_formula

https://www.umsu.de/trees/#~6x~9Fx~5~9~6xFx (∀x◇Fx→◇∀xFx)
https://www.umsu.de/trees/#~8~7xFx~5~7x~8Fx (□∃xFx→∃x□Fx)

**Comment by wo** [comment]
I don't see why this is an issue. The converse Buridan formula is invalid in standard constant domain semantics, and the prover correctly displays a countermodel.
