### ISSUE TITLE
TPG should not allow nested quantifiers with the same variable.

### ISSUE THREAD

**Issue by CCHeckman** [wo/tpg#27]
TPG says that ∀x∃x(P(x)→P(x)) is valid, but there are two nested quantifiers with an x in them, making this formula badly-formed.

**Comment by wo** [comment]
The formula is certainly "badly" formed, but it's controversial whether it should count as well-formed. Some textbooks say yes, some no. I want to err on the liberal side.

**Comment by CCHeckman** [comment]
> The formula is certainly "badly" formed, but it's controversial whether it should count as well-formed. Some textbooks say yes, some no. I want to err on the liberal side.

Actually, it is legal (by convention, the variable belongs to the innermost quantifier), but it's a bad habit to allow it.
