### ISSUE TITLE
Feature request more infix operators

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [wo/tpg#9]
Would it be possible to have more infix operators?
Recently the tool introduced = , which gave it
a nice boost, since its also supported by the 

proof search and the model finder. I wonder
whether it would be possible to also introduce
an infix operator ∈, so that one can write x∈y.

I am currently writing Exy. Unfortunately I don't
know how to extend the proof search and the model
finder, many things work already with the existing

proof search and model finder, for example FOL is
already able to derive a lot of theorems that talk about
x∈y without invoking anything from a set theory such

as for example ZFC. So the syntax would be already
useful only on the surface, without adding something to FOL.

**Comment by Jean-Luc-Picard-2021** [comment]
Or maybe fork your web site, and work towards a set theory 
version. Do you even have a license that would allow a
forking your web site. I am not saying that I have the resources

to do that, just curious hypothetically whether what you expect.

**Comment by Jean-Luc-Picard-2021** [comment]
Or maybe fork the web site to start a set theory branch?

A model finder could generate finite set theory models,
like ackerman encoding or whatever. And ZFC without the 
axiom of infinity, could parallel it by proof search,

but this proof search might be difficult to implement?

**Comment by wo** [comment]
These are natural ideas, but I don't think I will ever tackle them. The textbook-style tree format that my prover tries to generate is inefficient for reasoning within substantive theories like ZFC or PA. For this kind of task, it is better to use more powerful provers like E or Prover9, or (even more powerful) proof assistants like Isabelle or Lean.

**Comment by Jean-Luc-Picard-2021** [comment]
Currently I am use your tree tool, be just adding instances
of ZFC axioms in the premisses, thus helping the tool a little.
I do the guess of the formula in the axiom of separation

and axiom of replacement, and your tool does the rest.
Works pretty well so far for small scale problems. It works
well when generating a proof, 

but counter models naturally don't look so good.

**Comment by Jean-Luc-Picard-2021** [comment]
Somehow I still miss the ∈ operator. It would allow me to more easily compare your tree tool what I am [currently backing](http://www.xlog.ch/izytab/moblet/en/docs/18_live/34_bil2022/paste23/package.html). I get:
```
/* Problem from Set Theory */
?- time(prove0('∀p∀q(∀x(x∈p⇔x∈q)⇒p=q) ∧ \
∀x(x∈u⇔r(x)) ∧ \
∀x(x∈v⇔r(x)) ⇒ \
u=v', 6, unicode)), !.
% Wall 4902 ms, gc 7 ms, 1830308 lips
```
The same works also in your tree tool, when I encode x∈y as Exy.
Thats quite interesting that the above theorem is agnostic to any
backround set theory and is purely logical:
```
(∀p∀q(∀x(Exp ↔ Exq) → p=q) ∧ (∀x(Exu ↔ rx) ∧ ∀x(Exv ↔ rx))) → u=v is valid.
[https://www.umsu.de/trees/#~6p~6q%28~6x%28Exp~4Exq%29~5p=q%29~1~6x%28Exu~4r%28x%29%29~1~6x%28Exv~4r%28x%29%29~5u=v](https://www.umsu.de/trees/#~6p~6q%28~6x%28Exp~4Exq%29~5p=q%29~1~6x%28Exu~4r%28x%29%29~1~6x%28Exv~4r%28x%29%29~5u=v)
```

**Comment by medovina** [comment]
I agree that having at least a few infix operators (e.g. +, -, *, >, maybe even ∈) would be convenient for some kinds of queries.

**Comment by Jean-Luc-Picard-2021** [comment]
Since yesterday I have my own prover running
with ∈ syntax. But it will not produce a tableaux proof,
rather a natural deduction proof:

/* Drinker Paradox, formulate with Sets */
17 ¬ ∀x: ¬ (x ∈ d ⊃ ∀y:(y ∈ d))
▶ Conclusion 1,16
https://qiita.com/j4n_bur53/items/55b5678826ee74e05bff

Should I close this ticket? I was wondering whether I
could fork your tool. But then I saw it needs PHP.
Is this required? Is there some server roundtrip?

The above tool needs no server, works completely
in the browser.

**Comment by wo** [comment]
Nice work.

I use PHP to minify the source (on the fly) and to turn debugging options on and off.
